In [3]:
import torch
import pandas as pd
import numpy as np

In [2]:
print(torch.__version__)

2.1.0


In [4]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.item()

7

In [6]:
scaler.ndim

0

In [9]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
MATRIX = torch.tensor([[1,2],
                       [2,4]])
MATRIX

tensor([[1, 2],
        [2, 4]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1,2,4],
                        [2,3,6]]])
TENSOR

tensor([[[1, 2, 4],
         [2, 3, 6]]])

In [16]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 2, 3])

In [20]:
random_number = torch.rand(size=(3,4)) 
random_number

tensor([[0.4640, 0.5215, 0.6826, 0.4377],
        [0.2711, 0.0949, 0.6067, 0.2177],
        [0.0781, 0.3717, 0.1200, 0.6431]])

In [21]:
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor

tensor([[[0.0174, 0.5347, 0.8758],
         [0.3146, 0.2739, 0.4799],
         [0.9638, 0.8953, 0.6742],
         ...,
         [0.0973, 0.8913, 0.4021],
         [0.4856, 0.2236, 0.5619],
         [0.2592, 0.5199, 0.4562]],

        [[0.8611, 0.3768, 0.6233],
         [0.2058, 0.8099, 0.6195],
         [0.4715, 0.0272, 0.6584],
         ...,
         [0.1656, 0.2044, 0.7354],
         [0.8524, 0.1058, 0.8152],
         [0.7871, 0.1038, 0.0927]],

        [[0.3726, 0.1582, 0.9961],
         [0.7334, 0.5170, 0.9281],
         [0.6760, 0.5254, 0.0624],
         ...,
         [0.7621, 0.6772, 0.1287],
         [0.7301, 0.2071, 0.6938],
         [0.0683, 0.7366, 0.3973]],

        ...,

        [[0.5435, 0.6995, 0.7659],
         [0.5704, 0.9933, 0.7227],
         [0.1406, 0.3737, 0.9550],
         ...,
         [0.4553, 0.7338, 0.6020],
         [0.2170, 0.2397, 0.2395],
         [0.8456, 0.4143, 0.0774]],

        [[0.8777, 0.8234, 0.9452],
         [0.8214, 0.7017, 0.7201],
         [0.

In [22]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [23]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros.shape

torch.Size([3, 4])

In [25]:
random_number.shape

torch.Size([3, 4])

In [27]:
zeros.matmul(random_number.T)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
zeros*random_number

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
ones = torch.ones(size=(3,4))

In [30]:
ones*random_number

tensor([[0.4640, 0.5215, 0.6826, 0.4377],
        [0.2711, 0.0949, 0.6067, 0.2177],
        [0.0781, 0.3717, 0.1200, 0.6431]])

In [33]:
ones[0][1] = 2

In [34]:
ones

tensor([[1., 2., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ones*random_number

tensor([[0.4640, 1.0431, 0.6826, 0.4377],
        [0.2711, 0.0949, 0.6067, 0.2177],
        [0.0781, 0.3717, 0.1200, 0.6431]])

In [36]:
ones.dtype

torch.float32

In [40]:
one_to_ten = torch.arange(1,10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
zeros_like = torch.zeros_like(one_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
float32_tensor = torch.ones(size =(3,4), dtype=None, device=None, requires_grad=False)
float32_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [55]:
float32_tensor.dtype

torch.float32

In [58]:
floa16_tensor = torch.ones(size =(3,4), dtype=torch.float16, device=None, requires_grad=False)
floa16_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float16)

In [59]:
floa16_tensor*float32_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
some_tensor = torch.tensor([2,4], device="mps")
print("dtype:", some_tensor.dtype)
print("shape:", some_tensor.shape)
print("device:", some_tensor.device)

dtype: torch.int64
shape: torch.Size([2])
device: mps:0


In [69]:
some_tensor+10

tensor([12, 14], device='mps:0')

In [70]:
some_tensor*10

tensor([20, 40], device='mps:0')

In [71]:
some_tensor-10

tensor([-8, -6], device='mps:0')

In [74]:
mat1 = torch.tensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
mat2 = torch.tensor([[1,2,3,4],
                    [4,5,6,5],
                    [7,8,9,6]])
mat1.matmul(mat2)

tensor([[ 30,  36,  42,  32],
        [ 66,  81,  96,  77],
        [102, 126, 150, 122]])

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0